### ISSUE TITLE
SlapperHuman::isSurvival()

### ISSUE THREAD

**Issue by Driesboy** [PMPlugins/Slapper#1]
Fatal error: Call to undefined method slapper\entities\SlapperHuman::isSurvival() in /Users/Ronny/Desktop/dries/Lobby 2/src/pocketmine/inventory/PlayerInventory.php on line 216

**Comment by Driesboy** [comment]
Is fixed for Genisys

**Comment by jojoe77777** [comment]
I'm currently working on a rewrite that will fix this.

**Comment by Driesboy** [comment]
working for Imagicalmine and Clearsky
