### ISSUE TITLE
slapper php7

### ISSUE THREAD

**Issue by ondraczsk** [PMPlugins/Slapper#13]
It can not run slapper in ImagicalMine PHP 7 when running the show this pardon for English translate Google Translator 

Fatal error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name in phar:///hlserver/27538/plugins/Slapper_v1.2.9.3.phar/src/slapper/main.php on line 18

**Comment by InfornoFire** [comment]
use the download from here, its a php7 beta build https://github.com/PMPlugins/Slapper/tree/php7

**Comment by ondraczsk** [comment]
But it is in php 7(slapper Php7)

**Comment by FuxonPlayz** [comment]
yes it is and u need to compile it using pmt.mcpe.me using ZipToPhar Tool
