### ISSUE TITLE
add command

### ISSUE THREAD

**Issue by imjayl** [PMPlugins/Slapper#15]
I add a command but when i hit the entity it doesnt work.

**Comment by jojoe77777** [comment]
(I'm 99% sure) You're not adding the command properly.

**Comment by imjayl** [comment]
Example please

**Comment by Driesboy** [comment]
work

**Comment by imjayl** [comment]
How?

**Comment by imjayl** [comment]
I actually do that
/slapper edit (id) addcommand match
But it doesnt work

**Comment by jojoe77777** [comment]
That would make the slapper try to run "match" as the console. If you want it to run as the player, use "rca {player} match".
