### ISSUE TITLE
All Mobs are Spawning as Slappers

### ISSUE THREAD

**Issue by CLiu13** [PMPlugins/Slapper#16]
Mobs spawned by spawn eggs are spawning as slappers, which prevents ClearLagg from removing the unwanted mobs.

**Comment by jojoe77777** [comment]
I am aware of this ([see issue on old repo](https://github.com/PMPlugins/Development/issues/16)), but not sure how to fix it.

**Comment by robske110** [comment]
Should be fixed with the IMPLEMTS SLAPPERENTITY

**Comment by CLiu13** [comment]
No, that did not fix it.

**Comment by TheNewHEROBRINEX** [comment]
Maybe this happen because slappers and normal entities have the same ids

**Comment by TheNewHEROBRINEX** [comment]
if you change the network id constant of the slapper entities and in the function spawnTo you put the real id it works

**Comment by robske110** [comment]
Make a PR?!

**Comment by TheNewHEROBRINEX** [comment]
it works but i'm not sure if it is the right way to fix the issue

**Comment by jojoe77777** [comment]
> if you change the network id constant of the slapper entities and in the function spawnTo you put the real id it works

Yes! Forgot about that.

Here's what's happening in PocketMine code:
https://github.com/PocketMine/PocketMine-MP/blob/913a1fdce409c27f504bf2df08817438335c261c/src/pocketmine/entity/Entity.php#L422-L446

(When the entity is registered, PocketMine stores its NETWORK_ID in $knownEntities. When you use a spawn egg, the createEntity function is called with the meta of the spawn egg (damage). The createEntity function checks if the meta provided is in the $knownEntities array, and if it is, spawns an entity of that type.)

Will be fixed shortly.

**Comment by Tolo0** [comment]
hope this problem gets fixed soon. good luck.

**Comment by jojoe77777** [comment]
> hope this problem gets fixed soon. good luck.

Thanks, I've already fixed the issue but haven't released it yet. It will be in the 1.3.0 update.

**Comment by Tolo0** [comment]
any chance you can release it on github?  pocketmine takes for ever to accept plugins lol.

**Comment by thebigsmileXD** [comment]
So. Fixed. When will we see an update?

And what was the problem? SlapperEntity not implemented correctly?

**Comment by jojoe77777** [comment]
@thebigsmileXD Soon.
Look at my message, 4 messages above yours.

**Comment by Tolo0** [comment]
any chance you can release it on github?

**Comment by jojoe77777** [comment]
Fixed in the [php7 branch](https://github.com/PMPlugins/Slapper/tree/php7) (Will soon be merged into master)

**Comment by Tolo0** [comment]
ok cool. Can't wait 😊

**Comment by jojoe77777** [comment]
By "soon" I mean when I finish Slapper 1.3.0. Hopefully some time in the next few days/weeks (It will have a lot of new features and I'm having trouble with it)

**Comment by Tolo0** [comment]
I just need mobs to work with it for my new server I'm creating. look forward to seeing what the new features are though 😉
