### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by GlitchPlayer** [PMPlugins/Slapper#17]
ImagicalMine Crash Dump Fri Mar 4 01:32:07 CET 2016

Error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name
File: /Slapper_v1.2.9.3.phar/src/slapper/main
Line: 18
Type: E_COMPILE_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN

Code:
[9] use pocketmine\event\entity\EntityDamageByEntityEvent;
[10] use pocketmine\event\entity\EntityDamageEvent;
[11] use pocketmine\event\entity\EntitySpawnEvent;
[12] use pocketmine\event\Listener;
[13] use pocketmine\Item\Item;
[14] use pocketmine\nbt\tag\Byte;
[15] use pocketmine\nbt\tag\Compound;
[16] use pocketmine\nbt\tag\Double;
[17] use pocketmine\nbt\tag\Enum;
[18] use pocketmine\nbt\tag\Float;
[19] use pocketmine\nbt\tag\Int;
[20] use pocketmine\nbt\tag\Short;
[21] use pocketmine\nbt\tag\String;
[22] use pocketmine\Player;
[23] use pocketmine\plugin\PluginBase;
[24] use pocketmine\utils\TextFormat;
[25] use slapper\entities\other\SlapperBoat;
[26] use slapper\entities\other\SlapperFallingSand;
[27] use slapper\entities\other\SlapperMinecart;
[28] use slapper\entities\other\SlapperPrimedTNT;

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

ImagicalMine version: 1.4 #0 [Protocol 45; API 1.14.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux ca3.server.pro 3.14.32-xxxx-grs-ipv6-64 #1 SMP Sat Feb 7 11:35:27 CET 2015 x86_64
PHP Version: 7.0.2
Zend version: 3.0.0
OS : Linux, linux

Loaded plugins:
ItemCasePE 1.0.8 by aliuly for API(s) 1.10.0, 1.13.0
CrateKeys 1.0.5 by CDFalcon, CDFalcon for API(s) 1.13.0
EconomyAPI 2.0.9 by onebone for API(s) 1.13.0, 2.0.0
EconomyShop 2.0.7 by onebone for API(s) 1.13.0, 2.0.0
BuyCraft 1.2.2 by Falkirks for API(s) 1.0.0
EssentialsPE 1.1.3 by LegendsOfMCPE Team for API(s) 1.13.0, 2.0.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNWvtz20hy/lcm1FXZThEUH6IedOkSW5ZyTiSLsbTlqphbqgEwIOcEYLAYQBTvcv97vu4ZgKCs
Vel294e4dm1gHj397q8H/Huv0pnqzUYH06PhdDQdH/V7qixN2Zv9vVdtCkz1zu/Orq/mny/P786/
fr3+2uv3MmWtXNLcmcxzU4naKlGY6F5Vmc7VYpGH1WJRyeVicZEaWQlphXsIVSRp8Rt+fSO0FVLY
QkVapiJKpbUil2Co30t0Sgfs36SyKFR59zAajAcng8mgWMly35bRvnUz+5nUOTakOBmCHP+j3yvS
eomxWVXWqt+LTKxInBOQe8qoelA5WMVfutosFuf87yeZQbqPG/d2Tkve44DR8J8jsN04eu3Gm0Ku
8+2+8a/vu9S2Urkqed3kmXWfK5W5v3nJwTNLtlb6uKkUL5u+uOzMZIWp85iXHr649JOpw9TRPHpx
4XleOw6PX1zG/sLrTl5c99mpbjx8cdXNypRu3ejldVWp8yUvfM4W81RunAnGz5nAuSEto38/Ssv6
GD9nirrSqV0sbtVjdWHKzIk6bqzhPd17i1ZYaaoVDfjo+OiVMz587Y4LmSJgljfSWXN89NqNV+A3
kl57x6/dNS+RZuLbL7fve4jPqpQRQvJ7b28o3r6b7WjiRpUPqgz+HJXSrj7VWfE2NCZVMn/X+7nf
W5LPy5TCGausNojy3mhwAGbCWqdxbzZE+JemMpHBqoNpvycLzWtGB4Mhli11hdfhK/9gQynvUx3S
nsExU6g5Q816lzqvH0UkJwPLPA9wrpjQOZNx8Ig/wbK0gS4eDoPDA7E3EjdXc3GDJHihQnEkRqPZ
ZDobH4mz81sxHo6m4vH48O6QRClWBegfDYaDMd7+pnLI1Zvgdegm74xtzscAv6T80uY+Sxqi4D+D
183P6c1z3Rns7+gQ4mFE1hViw5JxZKrrdENaZxV+Jx06FvAAbmhG5RJhDvYSmVrk2lgV4Ja2Y9Ka
pPrUHeBMPfOEFwsNViKwUsDsVz6JG0myzq9vbr9df738hKG1Ci1W9mZ5naYQ8KyUlfovtbEdobZj
T2Wa7sp09gmOHxk6qn3cEfD3yNVy8SpxequqKuxsfx8euarDQWSy/Yan/XkbEcHVPJh7m0L6c8ya
bPNh/rkjfmewK/8Y8p/sym9yFeL/H2Xu8+rfLrsnjAzgeAF15PYuX68wrV+P7Fz8KB2PPhXv6I8U
r6vHf0JUC8ZaWT2XrxD2Y72BwyRVR9J2aNeLx5wGOmLCSe51eW935Pw91gvrTUQHAwlsWXiNwayl
jI+TdnLMzvCuLKPBZFeWS7Ukdq6Tq7P5ubhVMvvjnbPLD6AT5FLlb4hOx6rjdH9Hxn9Q4pUlpK9U
2TDTFgXUP6qJILo3b9/EmckTvRSEcxf53kWpxZUsxYEYoi6MZ8NpUxcOF/kShDOg2NPhIncKCEq4
26lJkkW+XoHhIAUedO+Ax3FkSuXeUuDFNCC7nH6Ezb4B96wWeSYfg4LBiz2dLnKYwwRWPmBPvsgt
gdCAiqiKKtjtlFjITBWf3mzr3P+Kbxs85+IverkS3//T6Fx8MeufQQwdQZ1Hyh8QyGilwUQGbVmm
X6rYVgigIEKuq1PJZ9AEIIlZB0kKil4Wx4rMdQY9d5jLTOheE1PipFY/vKl4KNxDrJNE44RqczqC
Ehk6VKYMrKoqYB972qjHKhW3L9T1nH46v/jw0+UtmIWeBwX6krUp49N/5T+tEX6pVbk5pS6DDrM8
lpolmdTz78BMAa2fHgynx2CDKnib3AebLCW3EFQvRMQeUZesEXYMAfnEZzQTGroi5AVPEbcrRZDL
CyFkqQSwloBGLR6ALyLXlIVK6DxK61jFeBA/+CPRujEZdiZE4ClNKxPVFwzjLJEUYankvdiYuvS0
hE4E1K4TzSfA6Up4DCo7CH9R65bcfqwSCTNYsTb5G3SDQIRwdfI6IF0SLd2AfTCBdpDFXq9ULupi
WcoYBAYLMrwnNlvkYu92VSqoGkPgIpX5ska/JajRY415tVuN99SAvv4b65S2nq1U5KXY3QgGmphX
+WCt73WhYi0Hplzu09s+tVx3Jrn7fHN9dzg5CcZ3tA9qbAnNxAIJarno0UHfVop0JyoDfvJYQEph
uZ+AmUqZAzNX0BtPszaZU/CBJ1WxSWP1oCMlVgDpKRs5A2Hn8tsjORFi3K7qKjYUHK47J2ZcwKKx
NlbFA3iOzO8tq4iCE6yQ1DBt18U8O//ipPhAMSkou9BqDy7Fg5biv8n5sYSDIPAzM+GiQeyhEK7R
28OnLeC78Ew5y0pPiO4NLKQs4DesDFRerERtiEmt24kADIWQYUv+nCOwoQMFCcp5At4NByJWw43w
boflPl7b2a3W9r5p2MXk8EAZx6JU1jkqsQnXvAc70tYlpy+6rQgV6QMKVL/UMiXrLTU6cvEg01qJ
t/5I5O13IO7OQ7JWlAECGH+5VOUMs3TylzoLYRxE3we7yaNbae8RIOU94m1A8z/BZt5WTkhatSoB
M2p4EFbbPq1PY+FTGzy8DzVk0JqlgstqQUWjsazOYWBawrRv2MPo9qUAk4/Ir5WCCiAOR0beskZa
dex8TiigaQkFbl/o6g00V5W8K1ZULNhpn+wVbyEB9Yhj0gjLEHgpZ0yJgpvSd7nh0P6P1IRQLJVy
4YbhfZmuKIVlainDTQWGxI1jZciHu9TrEgNkWmtmjJUtqKQ4Oo3+Lesl0XAXuD7fpxCVBCmlOdGZ
H8LU7LRLAzkMRRLpDOcsmcmAGZuJ4YIzC+fwCplJxv/P2SdY9ALzhCB+F/Mo7wWf7zNby4+nZgVC
ioqqihtu6MyGpdFwfOC4mqtSG65eFIuWDow4f3vu2ngb4Sikmph8jFcE1Iu5SOOsb4DVckQo9EbZ
4dfU6tQJSJVyQaBYd8sWXJ6JBqJvG8kuHdEJ15RCqCDy8sGPi0lsj16hQrryTDRXbCWIV6djt7cV
AJpUhd2KORl6Oe27ZxnyUk+c1EtZhrB/EJk0dVCOIuxZrbI7ESt+j/B7ELuZzGuu0F0uAF5q+MK7
fpMTnjiD9waXV5OkyQ3Z1ssG4tqVR36DR6xMncYtIxoZZJ2LLevkt6JgziHg4XDoZBR7FxwJP+RG
9hW3uxUqKU3WpFja6+eDblbq2BRCeNM9dYVn/Kezj9B1tKpRap2+L9nrKSHyIHFGrQdJIxxI7nN4
lsAr1i0KCDIQ9NnSIlKNmX2gnBx6Pj8Zt+2p+agIELBy27oU3Cl+2R8gMxciIHr4rpO6wcP+IJpo
q/eLpBZ5riqyRYv04Bqpq4ShrNBNEBCRBKFRAOFPPitxADoc62ddMgpVWxM53ex101czQ4Ffbiqi
3RfBqOPMVPv42KBqWEFamR66rLKttdw8UKGLXbrzBnR7Meh5GnDDBPWeAjrDcc/mP/WxFxyEyD9r
HVcrl7U5vlvyAZOfiSMPDLaQwcG5ztKB+BAjnlYyTfbREzgUEyv4mT8IRzr/M3k3INvq3KHVwUnn
jxR8BINk2neBTQd/0zlAJ8SC2yh2bar1P83zeYMUthCfQBBtWiPXLwjf50XgX7uYDL2UCuulM7/x
OVNQtSjZodWjimoHdij50PXooJ215BGMYYpVMdC5JjZGHr/8WYwIt/giRQCVT2rAKe+lNOVB68Jb
deYIOMhpxb6tZFXD9/aXkbMSUmRsO/w3XeVOx6IaPEoqgFJcr8ZLvaeS5th3ItijYmf1WwK3ZSYy
TC19JwOB+AMXsQvvhb9zfpM79JGEqResOsdDIdWP3HC4sxfsfbm+PZ8JTuD4L6rR1uVo65iQzoqU
wTCz509u2Wu95cOO4SP0HUhKXlZ2SK5u4IQcsCInHA99NaKs6IoceSTdTNC4r2w+gewON+nQweob
inwSMJRWdQ57O0LMPXNKX4wxMXpuQlXR4B3Hv1VdLtgdbokyNXX+IkUo5Dh3HqEIZ0lun7d9NeUU
bqgIiFFmkelabqyj7el0/GgNN1ip8oknmeWSOxy71hWd2IYIwtEnLeF3NsAdAQEXsyun8ZwbMbeC
7N5t6Skp9RnV/zvsF5WUtco3tu1BKvHMxdh25f43R/aKDym3rZc/ruMif6HiIvNNgyUckzL3jksW
bHiMawJt/ybmdQX3bhqMEg0u+ujYZIueS4Lo1NA6eHpUlLz+/MhM+OVQ7U6VZb1+yEydd8u09ci6
sS95BhmKGjsQpceZOPj1rbKkb6XOLRyNXWwgRifjZ3ez/LlylwOhctRClVC94Psvsj7pp6XqbsU6
BcrVpxv5oOj7OhI33YEoapKLjb/v8YihhZ2swkTaih2W9eKLTVKnvMxYZIGAsp+OXMHnRrmkSxbE
HMg2qvqrcb7CPYDMKAwzrmgEA1r5Wz93xiCFNsa4ko9CPtULOtWIq/g21HZtwfH/Vca6tp1t3g7S
c8f5z231IU3rgSkp3dPVY1AXsWR3aXw1SpV0h/A96xarOMa37XfD++BH5n1pWUvNNym/1KpW3r5+
P2dUHg8sjDUTx7+JWmGKOvXU/DMBiCeEFzmnuwDaI6bdFWvAfmRJk6TKDGWwovTjR0c+89JN8Uw4
CN6YlL7Q1gUgqcPlziE5Lzs46GmByhHt8gcS0Sm9riUd1A7ymMxCDc93S/wltbtJmbk8T5c+9JVY
uFF/seWcxHmv77faukF+HdCt3e5Im193RgEgdJ6YrRusDNmejxx07nABV5m/3OSbjJoxjhAL/dqW
Ueou/bTYTjPD8DUp5HKJwu6vcNrLMcrT9K38/nlpHD9Ezj7HT6pRthwL54+S6rZ7IeAD5/FfZWbC
P/AULEvN+0x8p8cAxarP3fzPDGuMC07RvdqkFNNeYC4FaYywAAE1B6LvxVuPpwZY8G7QCrINI/j0
0vnhnnhVeXMbniPVtB1hCoW0KUV8nwL5HZ38zEec+Xt2QlsaR/DatgNluIR9XDuFT3+QxlLddpK6
u4JtjyDoljZTacXtA7ewYV1ymqYbWcF9hWU4wWWdU2cDC7v37gwDm1bQ9ePNVwvGus9d4zMvjCos
Izg6NQOw0zC4h1wdF+BTmQGnbvr0QfHOdWx72kxcXH64nY3fH/WnJ4+j/uRx0h+/H72PgYxcqntb
lQovSEunx0OxRFBY93YwfcdfObS/U95+5/Cf7NRjpXLyOP6Cf4aq1vmxA2XezmsR7czaX1JdqQn/
GOMoiNUD/TzC/TqjWRJG8L5VZ4Au1fNYlt0h/8u29r0u085rolNko+5A1f09xjLuvmTdqRVSg/vh
AV7+aptfp/BrFrrb/85yoPlNUXUGbuaXO8IDdnelryQJ0j2+MFY/dt/9dQr/XmTEv374qhJ/FdAl
tcpMl3HL6cN2edtA2fzDE/8kppgZjUnrIuAfrAwPhkd4/NNneNCROhonJ4cnw3B0cHIsRyG4OJKH
k6NoMpHHk1E0jMfJ4XQq/gTa8xWbY+yPqsy9ylGYuioHjrwvVcKWhiQY2Uj+VsZfgr+eHZLldeG+
KbtvxMyn7tD4H6oQ13OuUH74kNi/oA+2/weRtSuT
===END CRASH DUMP===

**Comment by jojoe77777** [comment]
Use https://github.com/PMPlugins/Slapper/tree/php7

**Comment by GlitchPlayer** [comment]
How would I compile it?

**Comment by jojoe77777** [comment]
Drop the folder in your plugins folder, also install DevTools. Start your server then type /makeplugin Slapper.

**Comment by GlitchPlayer** [comment]
ok
slapper folder only?

**Comment by jojoe77777** [comment]
Yes

**Comment by GlitchPlayer** [comment]
In Devtools? or in plugins folder?

**Comment by jojoe77777** [comment]
plugins folder
