### ISSUE TITLE
Slapper NPC's Arent Saving

### ISSUE THREAD

**Issue by XShockinFireX** [PMPlugins/Slapper#19]
Everytime i add a Slapper NPC and i restart the server the NPC is gone

**Comment by XShockinFireX** [comment]
plz help

**Comment by Dergercol** [comment]
+++

**Comment by jojoe77777** [comment]
Not happening for me; I've tested multiple times.

**Comment by XShockinFireX** [comment]
Really? Well idk what im doing wrong :l
