### ISSUE TITLE
slapper php7

### ISSUE THREAD

**Issue by Driesboy** [PMPlugins/Slapper#2]

**Comment by jojoe77777** [comment]
https://github.com/PMPlugins/Slapper/tree/php7

**Comment by Driesboy** [comment]
work but slappers remove

**Comment by Driesboy** [comment]
can you make a updater

**Comment by Driesboy** [comment]
my slappers are now dead and i have more than 100 slappers :(

**Comment by jojoe77777** [comment]
What happened?

**Comment by legoboy0215** [comment]
Lol.

**Comment by jojoe77777** [comment]
> Lol.

What?

**Comment by Driesboy** [comment]
work

**Comment by jojoe77777** [comment]
> my slappers are now dead and i have more than 100 slappers :(

What made that happen? I want to know so others don't have that problem.

**Comment by Driesboy** [comment]
Its fixed
