### ISSUE TITLE
Add support for Api 2.0.0 / PHP 7

### ISSUE THREAD

**Issue by fdfdffdf** [PMPlugins/Slapper#21]
Pls add support for PHP 7 as I can't use it on my server cos it comes up with this error when I change the api:
Error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name
File: /Slapper/src/slapper/main
Line: 18
Type: E_COMPILE_ERROR

**Comment by TheNewHEROBRINEX** [comment]
Use this https://github.com/PMPlugins/Slapper/tree/php7

**Comment by fdfdffdf** [comment]
ok thx
