### ISSUE TITLE
I'm Sorry If im Such A Noob :(

### ISSUE THREAD

**Issue by kullza** [PMPlugins/Slapper#29]
Here What I'm Doing : 1. I download The Zip 2.I Extract the Slapper-Master 3.I Rename The Zip To Phar 4. I Copy the file and paste to Pocketmine/Plugin After that i download Devtools And Them i type Plugins And still its dont show Slapper Plugin...

[I'm Sorry About My English]
Hope U Guys Can Help Me :)

**Comment by kullza** [comment]
Im sorry My Bad I Extract the Folders And Rename The Zip To Phar :)

**Comment by Tolo0** [comment]
it's ok we were all noobs at the begging. 
1st put the slapper folder into ur plugin folder.  you don't rename it to phar. u just extract the zip so the folder is called slapper.master 
then reboot ur server. then on the console. type this

makeplugin slapper

then if done correctly they will be a slapper phar inside DevTools folder... or you could just use this online tool to convert it to a Phar.  u just upload the slapper.zip to it. 
http://pmt.mcpe.me/pocketmine.php

**Comment by kullza** [comment]
@Tolo0 So I Do What U Said...When i type makeplugin slapper its said = Invalid Plugin Name

**Comment by kullza** [comment]
@Tolo0 And i use the Online To Convert it The Server Crashed [Server] [10:51:33] [Server thread/WARNING]: Timezone could not be automatically determined. An incorrect timezone will result in incorrect timestamps on console logs. It has been set to "UTC" by default. You can change it on the php.ini file.
[Server] [10:51:34] [Server thread/INFO]: 
[Server] 
[Server] 		 PocketMine-iTX Genisys is a fork of PocketMine-MP, made by iTX Technologies LLC.
[Server] 		 Version: 1.1dev-383
[Server] 		 Target client Version: v0.14.2 alpha
[Server] 		 Latest source codes are available on https://github.com/iTXTech/Genisys
[Server] 		 Donate link: http://pl.zxda.net/plugins/203.html
[Server] 		 如果你在免费使用本核心，希望你可以进入上面的链接捐赠给我们，这会成为我们前进的动力。
[Server] 		
[Server] 
[Server] [10:51:34] [Server thread/INFO]: Loading pocketmine.yml...
[Server] [10:51:34] [Server thread/INFO]: Loading genisys.yml...
[Server] [10:51:34] [Server thread/INFO]: Loading server properties...
[Server] [10:51:34] [Server thread/INFO]: Selected English (eng) as the base language
[Server] [10:51:34] [Server thread/INFO]: Starting Minecraft: PE server version v0.14.2 alpha
[Server] [10:51:34] [Server thread/INFO]: Opening server on 0.0.0.0:19132
[Server] [10:51:34] [Server thread/INFO]: This server is running Genisys version 1.1dev-383 "Ikaros" (API 2.0.0)
[Server] [10:51:34] [Server thread/INFO]: Genisys is distributed under the GPL License version 3 and later
[Server] [10:51:36] [Server thread/INFO]: Loading DevTools v1.10.0
[Server] [10:51:36] [Server thread/INFO]: Enabling DevTools v1.10.0
[Server] [10:51:36] [Server thread/INFO]: [DevTools] Registered folder plugin loader
>makeplugin slapper
[Server] [10:51:36] [Server thread/INFO]: Preparing level "world"
[Server] [10:51:36] [Server thread/INFO]: Preparing level "nether"
[Server] [10:51:37] [Server thread/INFO]: Starting GS4 status listener
[Server] [10:51:37] [Server thread/INFO]: Setting query port to 19132
[Server] [10:51:37] [Server thread/INFO]: Query running on 0.0.0.0:19132
[Server] [10:51:37] [Server thread/INFO]: Default game type: Survival Mode
[Server] [10:51:37] [Server thread/INFO]: Done (8.765s)! For help, type "help" or "?"
[Server] [10:51:37] [Server thread/INFO]: Invalid plugin name, check the name case.
>makeplugin slapper
[Server] [10:51:41] [Server thread/INFO]: Invalid plugin name, check the name case.
[Server] [10:54:02] [Server thread/INFO]: Disabling DevTools v1.10.0
[Server] [10:54:02] [Server thread/INFO]: Unloading level "world"
[Server] [10:54:02] [Server thread/INFO]: Unloading level "nether"
[PocketMine] Server is starting...
[PocketMine] Server was started.
[Server] [10:54:07] [Server thread/INFO]: Stopping other threads
[Server] [10:54:08] [Server thread/WARNING]: Timezone could not be automatically determined. An incorrect timezone will result in incorrect timestamps on console logs. It has been set to "UTC" by default. You can change it on the php.ini file.
[Server] [10:54:08] [Server thread/INFO]: 
[Server] 
[Server] 		 PocketMine-iTX Genisys is a fork of PocketMine-MP, made by iTX Technologies LLC.
[Server] 		 Version: 1.1dev-383
[Server] 		 Target client Version: v0.14.2 alpha
[Server] 		 Latest source codes are available on https://github.com/iTXTech/Genisys
[Server] 		 Donate link: http://pl.zxda.net/plugins/203.html
[Server] 		 如果你在免费使用本核心，希望你可以进入上面的链接捐赠给我们，这会成为我们前进的动力。
[Server] 		
[Server] 
[Server] [10:54:08] [Server thread/INFO]: Loading pocketmine.yml...
[Server] [10:54:08] [Server thread/INFO]: Loading genisys.yml...
[Server] [10:54:08] [Server thread/INFO]: Loading server properties...
[Server] Server has stopped
[Server] [10:54:08] [Server thread/INFO]: Selected English (eng) as the base language
[Server] [10:54:08] [Server thread/INFO]: Starting Minecraft: PE server version v0.14.2 alpha
[Server] [10:54:08] [Server thread/INFO]: Opening server on 0.0.0.0:19132
[Server] [10:54:08] [Server thread/INFO]: This server is running Genisys version 1.1dev-383 "Ikaros" (API 2.0.0)
[Server] [10:54:08] [Server thread/INFO]: Genisys is distributed under the GPL License version 3 and later
[Server] [10:54:10] [Server thread/INFO]: Loading Slapper v1.2.9.4
[Server] 
[Server] Fatal error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name in phar:///storage/emulated/0/PocketMine/plugins/phar_Slapper-master_96DTNIeRMvuE2Sb.phar/src/slapper/main.php on line 18
[Server] [10:54:10] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[Server] [10:54:10] [Server thread/EMERGENCY]: Please upload the "/storage/emulated/0/PocketMine/crashdumps/CrashDump_Wed_May_18-10.54.10-UTC_2016.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
[PocketMine] Server was stopped.
[PocketMine] Server was stopped.

**Comment by kullza** [comment]
Whoops Sorry Wrong This Is The Real One2016-/INFO]: Loading Slapper v1.2.9.4
2016-05-18 [10:54:10] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
2016-05-18 [10:54:10] [Server thread/EMERGENCY]: Please upload the "/storage/emulated/0/PocketMine/crashdumps/CrashDump_Wed_May_18-10.54.10-UTC_2016.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.

**Comment by Tolo0** [comment]
post the crash dumb. and using genisys you don't need DevTools. Genisys has a plugin convertor already.

**Comment by kullza** [comment]
This is the Crash Dumps Genisys Crash Dump Wed May 18 11:21:11 UTC 2016

Error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name
File: /phar_Slapper-master_96DTNIeRMvuE2Sb.phar/src/slapper/main
Line: 18
Type: E_COMPILE_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
此次出错由插件引起

Code:
[9] use pocketmine\event\entity\EntityDamageByEntityEvent;
[10] use pocketmine\event\entity\EntityDamageEvent;
[11] use pocketmine\event\entity\EntitySpawnEvent;
[12] use pocketmine\event\Listener;
[13] use pocketmine\Item\Item;
[14] use pocketmine\nbt\tag\Byte;
[15] use pocketmine\nbt\tag\Compound;
[16] use pocketmine\nbt\tag\Double;
[17] use pocketmine\nbt\tag\Enum;
[18] use pocketmine\nbt\tag\Float;
[19] use pocketmine\nbt\tag\Int;
[20] use pocketmine\nbt\tag\Short;
[21] use pocketmine\nbt\tag\String;
[22] use pocketmine\Player;
[23] use pocketmine\plugin\PluginBase;
[24] use pocketmine\utils\TextFormat;
[25] use slapper\entities\other\SlapperBoat;
[26] use slapper\entities\other\SlapperFallingSand;
[27] use slapper\entities\other\SlapperMinecart;
[28] use slapper\entities\other\SlapperPrimedTNT;

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

Genisys version: 1.1dev #383 [Protocol 60; API 2.0.0]
uname -a: Linux localhost 3.10.28-580833 #1 SMP PREEMPT Thu May 14 19:12:06 KST 2015 armv7l
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, android

Loaded plugins:
加载的插件:

**Comment by legoboy0215** [comment]
Use the PHP_7 branch

**Comment by Tolo0** [comment]
what he sed ^^

**Comment by kullza** [comment]
I'm Sorry, Where Can I Download The Zip ??

**Comment by kullza** [comment]
Nevermind I Just found it ty :)

**Comment by kullza** [comment]
WUHU!!I finally Add The Plugin Thank You For you Help @Tolo0 @legoboy0215
