### ISSUE TITLE
=))A glich

### ISSUE THREAD

**Issue by astersx** [PMPlugins/Slapper#3]
ClearLagg remove slappers :0  .....

**Comment by legoboy0215** [comment]
Exclude Slapper entities.

**Comment by Driesboy** [comment]
fixed

**Comment by astersx** [comment]
Yay thx 😍😄😳😍😍😍😍😍😍😍😍😍😍😍😍

**Comment by astersx** [comment]
Crash 😢
![screenshot_2016-02-12-17-45-33](https://cloud.githubusercontent.com/assets/13157548/13011811/53c30de4-d1b1-11e5-8521-daf74d30d212.png)

**Comment by astersx** [comment]
The bad thing is that,  the server freeze, i could not terminate screen and i rebooted all!! -.-'

**Comment by Driesboy** [comment]
open a other issues it is a other problem
