### ISSUE TITLE
Slappers not spawning

### ISSUE THREAD

**Issue by NGGNewGen** [PMPlugins/Slapper#30]
Before anyone says I'm not **I'm using php7** anyway so I do /slapper spawn Human and then the name. And I get a message saying An error has occurred whole perfoming this action. Why is it doing  this and I use slappers for mostly floating text and running commands but it just wont work 👎

**Comment by jojoe77777** [comment]
If you're not using php7 for your server, use https://github.com/PMPlugins/Slapper. Otherwise use https://github.com/PMPlugins/Slapper/tree/php7

**Comment by jojoe77777** [comment]
Are you using php7 on both the server and the plugin? And please send the console error.

**Comment by NGGNewGen** [comment]
05 20:51:58 [Server] Server thread/CRITICAL ClassNotFoundException: "Class slapper\Compound not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144
26.05 20:51:58 [Server] Server thread/CRITICAL Unhandled exception executing command 'slapper spawn human ' in slapper: Class slapper\Compound not found

There's the error and yes I'm using **Genysis PhP7 for 14.3**

**Comment by NGGNewGen** [comment]
And i got the plugin from the PhP7 Branch

**Comment by jojoe77777** [comment]
> And i got the plugin from the PhP7 Branch

You sure? Doesn't seem like it. Double-checked the php7 branch and it all looks fine, no 'Compound's, just 'CompoundTag's.

**Comment by NGGNewGen** [comment]
OK it's working
