### ISSUE TITLE
Slappers are not saving.

### ISSUE THREAD

**Issue by SirOptic** [PMPlugins/Slapper#31]
Hello I am an owner. Of a netherbox server.For some reason when slappers are placed it works.And are saved for a couple of hours,but once the servers closes they disapear can you please fix this issue I don't. Know whats going on, but it is getting annoying i can't. Place any slappers.Btw i am using geneysis software.

**Comment by biswarm22** [comment]
same with me , when i edit slappers, they do not save after a couple hours

**Comment by jojoe77777** [comment]
I have tried many times to reproduce this but can't.

**Comment by legoboy0215** [comment]
It works for me too...
