### ISSUE TITLE
Can't get Slapper 1.2.9.4 working

### ISSUE THREAD

**Issue by GigAbove** [PMPlugins/Slapper#32]
I have a netherbox.com Genisys. 0.14 server. When I copied the slapper_v1.2.9.4.phar to my plugin folder, this is the error I get. Help. 

09.06 04:32:32 [Server] Server thread/CRITICAL UnexpectedValueException: "internal corruption of phar "/plugins/Slapper_v1.2.9.4.phar" (__HALT_COMPILER(); not found)" (EXCEPTION) in "/src/pocketmine/plugin/PharPluginLoader" at line 85
09.06 04:32:32 [Server] Server thread/ERROR Could not load '/plugins/Slapper_v1.2.9.4.phar' in folder '/plugins/': internal corruption of phar "/plugins/Slapper_v1.2.9.4.phar" (__HALT_COMPILER(); not found)
09.06 04:32:32 [Server] Server thread/INFO Genisys is distributed under the GPL License version 3 and later
09.06 04:32:32 [Server] Server thread/INFO This server is running Genisys version 1.1dev-ed69af7

**Comment by jojoe77777** [comment]
Download the phar again, "internal corruption of phar"

**Comment by GigAbove** [comment]
Same message. I downloaded the. Phar from here https://github.com/PMPlugins/Slapper/find/php7?q=

Is that the correct link?

**Comment by jojoe77777** [comment]
Works fine for me, try the direct link: https://raw.githubusercontent.com/PMPlugins/Slapper/php7/Slapper_v1.2.9.4.phar

**Comment by GigAbove** [comment]
Great!  That worked!!  No errors.  Now to try to use it.  Do you know where I can find a list of commands?

**Comment by GigAbove** [comment]
Great that worked for me!  One last question.  I Spawned a sheep.  
1. It doesn't move.
2. I can't sheer it

Do I need to load something else or some other plugin to enable this?

**Comment by legoboy0215** [comment]
@GigAbove 
1. They aren't supposed to move.
2. I don't think you are supposed to shear it.
3. /slapper remove then hit the sheep.

**Comment by GigAbove** [comment]
Oh..... So is there a plugin, for pocketmine PHP7, that has mobs that you can interact with.  i.e. move, sheer, kill?

**Comment by legoboy0215** [comment]
With AI? Yes. https://github.com/milk0417/EntityManager
https://github.com/milk0417/PureEntities

Don't expect too much.

**Comment by GigAbove** [comment]
Ok, I just wanted sheep or spiders or growing trees for my pocketmine server.  I guess I will keep searching.....

I am new to this and I thought the pocketmine server would function the same as MCPE.  I was hoping the slapper plugin was my answer to the missing mobs.

**Comment by legoboy0215** [comment]
@GigAbove TBH, PM is not complete at all. But it has the most plugins and has the longest history.

**Comment by Dog2puppy** [comment]
@GigAbove You said it's a Genisys Server. Genisys has Mobs, Weather, and Redstone built in. You enable it in Genisys.yml
