### ISSUE TITLE
add command doesn't work.

### ISSUE THREAD

**Issue by ABAxStorm** [PMPlugins/Slapper#33]
Whenever I add an entity to make players go to PvP, it won't work.

I used /slapper edit 697 addcommand /warp PvP but it didn't work. (I've also tried just warp pvp)

**Comment by ABAxStorm** [comment]
Nvm fixed it.

**Comment by MajorPlayz** [comment]
I have the same problem @ABAxStorm how did u fix it?

**Comment by jojoe77777** [comment]
@MajorPlayz Different for each warp plugin, but try /slapper edit <id> add command rca {player} warp <warpname>

**Comment by MajorPlayz** [comment]
Thanks @jojoe77777
