### ISSUE TITLE
Slappers Do Not Save

### ISSUE THREAD

**Issue by ABAxStorm** [PMPlugins/Slapper#34]
I have a NetherBox server, which runs Genisys. When the server restarts, all slappers are removed and have to be placed again. Please fix this!

Reproducing the issue:
Run Genisys server software
Install Slapper PHP7
Create an entity, with a command and name.
Restart server.

**Comment by jojoe77777** [comment]
Cannot reproduce. Have tried many times on PocketMine, Genisys etc.

**Comment by ABAxStorm** [comment]
Try it with multiple entities.

**Comment by XShockinFireX** [comment]
I'm having the same issue
