### ISSUE TITLE
Question: Aren't slappers sopposed to look at you when your near them? 

### ISSUE THREAD

**Issue by Dog2puppy** [PMPlugins/Slapper#35]
I was wondering, aren't slappers sopposed to look at you and face you as you move. (Ex: MobCrush Server). Or is this a different plugin?

**Comment by XShockinFireX** [comment]
This is a different plugin.

**Comment by Dog2puppy** [comment]
Do you know what plugin, @XShockinFireX?

**Comment by MajorPlayz** [comment]
The plugin is called NPC and if u have kik or something tell me here and I can send it to u if u want. Just do you know though, it isn't as good as Slapper as Slapper has tags like {line} and {display_name} so it is up to u if u want slapper or NPC or both. I have both but I use slapper more. Have Fun

**Comment by MajorPlayz** [comment]
@Dog2puppy my kik is kingofthegod

**Comment by jojoe77777** [comment]
Different plugin. https://github.com/onebone/NPC @MajorPlayz No need.

**Comment by MajorPlayz** [comment]
Oh ok :)

**Comment by jojoe77777** [comment]
@MajorPlayz Might wanna remove your kik name since this is public.

**Comment by XShockinFireX** [comment]
@Dog2puppy The plugin is called FNPC. https://coding.net/u/FENGberd/p/FNPC/git

**Comment by MajorPlayz** [comment]
Thanks @joejoe77777
