### ISSUE TITLE
you can hit slappers in 0.15.0

### ISSUE THREAD

**Issue by Driesboy** [PMPlugins/Slapper#37]

**Comment by jojoe77777** [comment]
Do they actually take damage/die?

**Comment by legoboy0215** [comment]
They take damage, like the ones on LBSG does.

**Comment by jojoe77777** [comment]
@legoboy0215 So their health actually goes down? I know the hurt animation is visible.

**Comment by legoboy0215** [comment]
IDK.

**Comment by SleepSpace9** [comment]
The EntityDamageEvent is fired, but the health of SlapperEntity fully resets after it's getting hurt. They don't get destroyed. My diamond sword wasn't able to kill it.  :grimacing:

**Comment by Driesboy** [comment]
No damage i think
Op 17-jun.-2016 12:18 schreef "SleepSpace9" <notifications@github.com>:

**Comment by jojoe77777** [comment]
@SleepSpace9 The EntityDamageEvent was always being fired, it's supposed to be.

Don't think I can fix this, or at least not via Slapper.
