### ISSUE TITLE
slappers not load

### ISSUE THREAD

**Issue by Driesboy** [PMPlugins/Slapper#38]
when you walk in the world and if there are NPCs who were not loaded then crashes the client

**Comment by jojoe77777** [comment]
Pretty sure there's nothing I can do about that, assuming it's a metadata problem.

**Comment by legoboy0215** [comment]
Same. I crash too.

**Comment by jojoe77777** [comment]
Try this and see if it works: ```<?php
​
/**
 * Temp patch
 *
 * @name Patch
 * @main jojoe\patch\Main
 * @version 1.0.0
 * @api 2.0.0
 * @description Patch
 * @author jojoe77777
 */
namespace jojoe\patch {
​
    use pocketmine\plugin\PluginBase;
    use pocketmine\event\Listener;
    use pocketmine\event\server\DataPacketSendEvent;
    use pocketmine\network\protocol\AddEntityPacket;
​
    class Main extends PluginBase implements Listener{
​
        public function onEnable(){
            $this->getServer()->getPluginManager()->registerEvents($this, $this);
	    }
​
        public function onPacketSent(DataPacketSendEvent $event){
            $pk = $event->getPacket();
            if($pk instanceof AddEntityPacket){
                $pk->metadata = [];
            }
        }
	}
}
​``` This will remove metadata from all entities.

**Comment by Driesboy** [comment]
Can you make fork? Or branch
Op 17-jun.-2016 08:42 schreef "jojoe77777" <notifications@github.com>:

**Comment by jojoe77777** [comment]
@Driesboy Found a better way that keeps the metadata, I'll make a script for that soon.

**Comment by Driesboy** [comment]
Can you do it so fast as posible
Op 17-jun.-2016 15:10 schreef "jojoe77777" <notifications@github.com>:

**Comment by Driesboy** [comment]
?

**Comment by Driesboy** [comment]
i have try your fix but spawned npcs are leashed
