### ISSUE TITLE
dont see name tag

### ISSUE THREAD

**Issue by Driesboy** [PMPlugins/Slapper#39]
you cannot see name tag from all npcs extent Human

**Comment by jojoe77777** [comment]
MCPE problem. Have tested with other entities too.

**Comment by kabluinc** [comment]
name tags and floating text visible when playing on a MiNet version of server for MCPE. So not MCPE issue

**Comment by Driesboy** [comment]
its a server problem i think

**Comment by BradleyJey** [comment]
I think its sometging with pocketmine

Get Outlook for iOS




On Tue, Jun 21, 2016 at 9:40 AM -0400, "Driesboy" <notifications@github.com> wrote:





its a server problem i think

---
