### ISSUE TITLE
Please re-add the config

### ISSUE THREAD

**Issue by XiangZhao969** [PMPlugins/Slapper#4]
So all commands could be more easier to be managed

**Comment by legoboy0215** [comment]
Why @jojoe77777? Can be done. Load commands from config at startup?

**Comment by jojoe77777** [comment]
I just wanna step away from the idea of storing commands in a config... But if you make a config.yml file and set it up properly, then type /slapper edit <id> update it should add the config commands.

**Comment by legoboy0215** [comment]
Options?
