### ISSUE TITLE
other slappers are leashed

### ISSUE THREAD

**Issue by Driesboy** [PMPlugins/Slapper#40]

**Comment by SleepSpace9** [comment]
I guess the lead metadata has also be added to other types of Slapper entities.

**Comment by daniktheboss** [comment]
If this is fixed close issue?

**Comment by Driesboy** [comment]
no

**Comment by daniktheboss** [comment]
None of mine are leashed.

**Comment by Driesboy** [comment]
not humans? other npc

**Comment by BradleyJey** [comment]
Slappers crash game! (Mobs, human works fine)

Get Outlook for iOS




On Wed, Jun 22, 2016 at 12:32 PM -0400, "Driesboy" <notifications@github.com> wrote:





not humans? other npc

---

**Comment by daniktheboss** [comment]
Nope! Nothing is leashed at all!

**Comment by Driesboy** [comment]
Do i need to replace my mobs?
Op 23-jun.-2016 17:49 schreef "daniktheboss" <notifications@github.com>:

**Comment by Dog2puppy** [comment]
On Genisys, Humans have leashes (I can walk myself as if I was a dog! XD). Also, mobs other than a human crash the client on Gneisys.

**Comment by BradleyJey** [comment]
QHuman Slappers Are LeashedAUpdate To Latest Plugin Version!!!
QSlappers other than human crash client ANo one knows why....
QFallingsand doesnt workABlock update cant be seen by client, FALSE! When u use world edit and paste something its block update and it can be seen by client, its something wrong with the plugin then? 0.15.0 sucks so much! It ruined servers....
Get Outlook for iOS




On Sat, Jun 25, 2016 at 2:41 PM -0400, "Dog2puppy" <notifications@github.com> wrote:





On Genisys, Humans have leashes (I can walk myself as if I was a dog! XD). Also, mobs other than a human crash the client on Gneisys.

---

**Comment by HittmanA** [comment]
Hey i still have the leash problem. I did /slapper spawn Player <message> and it was leashed to me.

**Comment by BradleyJey** [comment]
This is the 82827226167282282726257228827262616162526262 time i say this, please update to the latest version. The plugin wont update itself when they update it lol

Get Outlook for iOS




On Sun, Jun 26, 2016 at 12:07 AM -0400, "HittmanA" <notifications@github.com> wrote:





Hey i still have the leash problem. I did /slapper spawn Player <message> and it was leashed to me.

---

**Comment by jojoe77777** [comment]
Fixed.

**Comment by BradleyJey** [comment]
Ok so now... When are all mobs gonna be fixed? And when will falling sand work?

Get Outlook for iOS




On Tue, Jun 28, 2016 at 7:10 PM -0400, "jojoe77777" <notifications@github.com> wrote:





Fixed.

---

**Comment by jojoe77777** [comment]
Mobs are fixed, name tags are on the TODO list.

**Comment by BradleyJey** [comment]
Ok Thanks, By the way, why does the new slapper version cannot be used as .zip?

Get Outlook for iOS




On Tue, Jun 28, 2016 at 7:56 PM -0400, "jojoe77777" <notifications@github.com> wrote:





Mobs are fixed, name tags are on the TODO list.

---

**Comment by BradleyJey** [comment]
I mean, i delete the new version of the slapper plugin and my server works just finebut when i install again it makes my servergo crazy

Get Outlook for iOS




On Tue, Jun 28, 2016 at 7:57 PM -0400, <bradley_2025@outlook.com> wrote:





Ok Thanks, By the way, why does the new slapper version cannot be used as .zip?

Get Outlook for iOS




On Tue, Jun 28, 2016 at 7:56 PM -0400, "jojoe77777" <notifications@github.com> wrote:





Mobs are fixed, name tags are on the TODO list.

---

**Comment by BradleyJey** [comment]
Wait, all nametags work, you just need to hold on the fallingsand or mob. The thing to do now is to make them visible from long distance.

Get Outlook for iOS




On Tue, Jun 28, 2016 at 7:56 PM -0400, "jojoe77777" <notifications@github.com> wrote:





Mobs are fixed, name tags are on the TODO list.

---

**Comment by TheProest35YT** [comment]
@dog2puppy same
