### ISSUE TITLE
FallingSand Doesnt Work At All

### ISSUE THREAD

**Issue by BradleyJey** [PMPlugins/Slapper#41]
When I Use /slapper spawn fallingsand ImFallingSand! It says it spawned it but it doesnt show name tag or the stone block itself like it used to.

**Comment by kabluinc** [comment]
Floating text particle has stopped working since the Minecraft update. I don't think much can be done server side to fix this

**Comment by BradleyJey** [comment]
No Plugin Can Make Floating Text?

Get Outlook for iOS




On Sat, Jun 18, 2016 at 12:51 PM -0400, "kabluinc" <notifications@github.com> wrote:





Floating text particle has stopped working since the Minecraft update. I don't think much can be done server side to fix this

---

**Comment by kabluinc** [comment]
I don't think so

**Comment by XShockinFireX** [comment]
Yeah, FallingSand wont work yet because block updates aren't visible to the client, unless you relog. This issue might get fixed soon.

**Comment by BradleyJey** [comment]
If I Spawn A Falling Sand Block, Then Relog, Will I Be Able To See It?

Get Outlook for iOS




On Sun, Jun 19, 2016 at 12:22 PM -0400, "XShockinFireX" <notifications@github.com> wrote:





Yeah, FallingSand wont work yet because block updates aren't visible to the client, unless you relog. This issue might get fixed soon.

---

**Comment by BradleyJey** [comment]
I Think So, It Happens With World Edit Too.

Get Outlook for iOS




On Sun, Jun 19, 2016 at 12:23 PM -0400, <bradley_2025@outlook.com> wrote:





If I Spawn A Falling Sand Block, Then Relog, Will I Be Able To See It?

Get Outlook for iOS




On Sun, Jun 19, 2016 at 12:22 PM -0400, "XShockinFireX" <notifications@github.com> wrote:





Yeah, FallingSand wont work yet because block updates aren't visible to the client, unless you relog. This issue might get fixed soon.

---

**Comment by kabluinc** [comment]
this falling sand floating text not showing up issue is apparently fixed with the MiNet mcpe server versions. So surely not a MCPE bug.

**Comment by jojoe77777** [comment]
I will see if I can fix this.

**Comment by BradleyJey** [comment]
Thanks joejoe777

Get Outlook for iOS




On Tue, Jun 21, 2016 at 8:51 PM -0400, "jojoe77777" <notifications@github.com> wrote:





I will see if I can fix this.

---

**Comment by jojoe77777** [comment]
I think I found the problem. https://github.com/PocketMine/PocketMine-MP/blob/master/src/pocketmine/Player.php#L1163-L1165

**Comment by kabluinc** [comment]
floating text Particle is fixed by Genisys https://github.com/iTXTech/Genisys/commit/97da0933c25410f8a5af69134d3212a9e0bfa57a 

but the Slapper falling sand does not show up

**Comment by BradleyJey** [comment]
Anyone know the link of NPC Plugin which looks at you when you walk past it?

Get Outlook for iOS




On Fri, Jun 24, 2016 at 10:35 AM -0400, "kabluinc" <notifications@github.com> wrote:





floating text Particle is fixed by Genisys https://github.com/iTXTech/Genisys/commit/97da0933c25410f8a5af69134d3212a9e0bfa57a

but the Slapper falling sand does not show up

---

**Comment by AndroidHackPro** [comment]
@BradleyJey I want to know that to!
