### ISSUE TITLE
Mobs crash the game

### ISSUE THREAD

**Issue by daniktheboss** [PMPlugins/Slapper#42]
When I do /slapper spawn wolf,creeper,chicken and other it crashes the game... but spawn human doesn't!

**Comment by legoboy0215** [comment]
Genisys issue?

**Comment by jojoe77777** [comment]
AddEntityPacket changed but AddPlayerPacket didn't. Metadata problem; I'll see what I can do.

**Comment by daniktheboss** [comment]
Yea I'm using genisys but when u use spawn eggs they move and no problems! And thanks

**Comment by daniktheboss** [comment]
Any news?

**Comment by Dog2puppy** [comment]
Anymore, lots of plugins will need different versions. One version for each PM fork. They're all changing so quick, that plugins will become USELESS!

**Comment by BradleyJey** [comment]
Learn Grammar. Those Plugins Not That Plugins.

Get Outlook for iOS




On Sat, Jun 25, 2016 at 2:50 PM -0400, "Dog2puppy" <notifications@github.com> wrote:





Anymore, lots of plugins will need different versions. One version for each PM fork. They're all changing so quick, that plugins will become USELESS!

---

**Comment by Troctor** [comment]
any updates on this?

**Comment by jojoe77777** [comment]
Server issue.
