### ISSUE TITLE
List ID's?

### ISSUE THREAD

**Issue by JoRa22** [PMPlugins/Slapper#44]
Hello, great plug.. thx!

Im not sure if you are able to do this or not, but is there a way to list all the slappers? For example, maybe with a command like '/slapper list' -- Then it gives you all the slapper ID's with the slapper name..  If this is not possible would you consider adding it?

-Also do you have a documentation page?

Thank you..

**Comment by legoboy0215** [comment]
Elaborate. What is a documentation page?

**Comment by JoRa22** [comment]
I found the documentation page: https://forums.pocketmine.net/plugins/slapper.1267/field?field=documentation

Now I just need to know if there is a way I can list all the slappers on my server including the name and entity ID?

**Comment by jojoe77777** [comment]
> Now I just need to know if there is a way I can list all the slappers on my server including the name and entity ID?
Not yet. I'll think about it. But it would require checking every entity in the world or server.

**Comment by JoRa22** [comment]
I see... Thank you for your response.

What if you created a log file. so that every slapper created by this plugin would be logged in there... Then a command such as /slapper list would list them all... Would that be easier?

**Comment by JoRa22** [comment]
not Sure why the thumbs down... it was just a quesion / suggestion... Im new at this and that was just rude

**Comment by jojoe77777** [comment]
> not Sure why the thumbs down... it was just a quesion / suggestion... Im new at this and that was just rude

I just meant that a log file wouldn't work.

**Comment by JoRa22** [comment]
ok.. thx anyway
