### ISSUE TITLE
Weird Line spawns when a NPC Is Spawned

### ISSUE THREAD

**Issue by TheProest35YT** [PMPlugins/Slapper#45]
Something just appears when i spawn in a NPC

**Comment by TheProest35YT** [comment]
![screenshot_2016-06-24-18-08-47_com mojang minecraftpe](https://cloud.githubusercontent.com/assets/19955608/16335021/e5491c66-3a36-11e6-8d0e-45743f33c083.png)

**Comment by jojoe77777** [comment]
Please update to the latest version.

**Comment by JoRa22** [comment]
I currently have the latest version Slapper_v1.2.9.4 and i still see the lead/rope attached... is this fixed? i have also updated the SlapperHuman.php.

How can I get rid of it?

**Comment by TheProest35YT** [comment]
Jojoe i did
