### ISSUE TITLE
Slapper doesn't work

### ISSUE THREAD

**Issue by HittmanA** [PMPlugins/Slapper#46]
I spawn a slapper with `/slapper spawn Player <message>` and it spawns fine. When I do `/slapper edit <id> addcommand killrate` and it says it added the command but when I slap it it does nothing. I tried a non-existent command (blah) and it doesn't even say "unknown command"

**Comment by jojoe77777** [comment]
> I spawn a slapper with /slapper spawn Player <message> and it spawns fine. When I do /slapper edit <id> addcommand killrate and it says it added the command but when I slap it it does nothing. I tried a non-existent command (blah) and it doesn't even say "unknown command" 

/slapper edit <id> addcommand rca {player} killrate

**Comment by HittmanA** [comment]
Thanks, sorry for the trouble.

**Comment by legoboy0215** [comment]
LMAO
