### ISSUE TITLE
Slapper talk... Let me explain. (Not an issue)

### ISSUE THREAD

**Issue by JUSTaMod** [PMPlugins/Slapper#47]
Let's say I have a slapper with a name, and I want it to tell a player something.
I can't use slapper edit (Id) add command tell {player} blah blah... It just runs in the console.
Is there a way to have the slapper actually say it's name when it's telling a player something when a tell command is run from it?

**Comment by jojoe77777** [comment]
...

**Comment by JUSTaMod** [comment]
Sorry. Lol. Hit submit before I made the description.

**Comment by jojoe77777** [comment]
https://github.com/PMPlugins/Feedback/issues

**Comment by jojoe77777** [comment]
https://github.com/PMPlugins/TellRaw

**Comment by JUSTaMod** [comment]
Well. K. Thx

**Comment by jojoe77777** [comment]
https://github.com/jojoe77777/Development Find TellRaw in there.

**Comment by jojoe77777** [comment]
https://github.com/PMPlugins/Development Find TellRaw in there.

**Comment by JUSTaMod** [comment]
K thanks. That was probably the worst worded and said "issue" submit I have ever done.

**Comment by JUSTaMod** [comment]
And tellraw will work with slapper the way I need it too?

**Comment by jojoe77777** [comment]
yes

**Comment by JUSTaMod** [comment]
Ok, i got some sleep. I really dont feel like opening issues so if you have a quick fix for this...
[Server thread/CRITICAL]: Unhandled exception executing command 'slapper spawn Player' in slapper: Call to undefined method pocketmine\Player::getSkinName()
[08:49:20] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\Player::getSkinName()" (EXCEPTION) in "/Slapper_v1.2.9.4.phar/src/slapper/main" at line 727
(It does this with every entity I try to spawn)

**Comment by Survingo** [comment]
Intyre edited getSkinName() to getSkinId()...

**Comment by jojoe77777** [comment]
> Intyre edited getSkinName() to getSkinId()...

Yes, so I did too. @JUSTaMod Update to the latest version.
