### ISSUE TITLE
Skin Issue, Wont Allow Any Spawns

### ISSUE THREAD

**Issue by Shadow166050** [PMPlugins/Slapper#48]
28.06 10:18:29 [Server] Server thread/CRITICAL Error: "Call to undefined method pocketmine\Player::getSkinName()" (EXCEPTION) in "/phar_Slapper_DaeVteeEAdcWnSD.phar/src/slapper/main" at line 727
28.06 10:18:29 [Server] Server thread/CRITICAL Unhandled exception executing command 'slapper spawn player test' in slapper: Call to undefined method pocketmine\Player::getSkinName()

I get it when ever I try to spawn something, it does it to all classes,  for example the Player will be replaced with Cow if I was spawning a cow

**Comment by Shadow166050** [comment]
Genisys changed SkinName To SkinId Sorry

**Comment by BradleyJey** [comment]
Hey who knows NPC Plugin link? As i can see floating text works well with NPC

Get Outlook for iOS




On Tue, Jun 28, 2016 at 3:11 PM -0400, "Shadow166050" <notifications@github.com> wrote:





Genisys changed SkinName To SkinId Sorry

---

**Comment by jojoe77777** [comment]
Fixed.
