### ISSUE TITLE
Phar 

### ISSUE THREAD

**Issue by SirOptic** [PMPlugins/Slapper#49]
Hello where can I find the latest phar.

**Comment by Thecraftdu34** [comment]
Hello ! you can use http://pmt.mcpe.me/pocketmine.php  it's very simple for compile :)

**Comment by BradleyJey** [comment]
Yes, i was gonna say that a lomg time ago i just forgot the link xD

Get Outlook for iOS




On Tue, Jun 28, 2016 at 10:37 PM -0400, "Thecraftdu34" <notifications@github.com> wrote:





Hello ! you can use http://pmt.mcpe.me/pocketmine.php  it's very simple for compile :)

---

**Comment by Thecraftdu34** [comment]
Ok xD

**Comment by jojoe77777** [comment]
https://raw.githubusercontent.com/PMPlugins/Slapper/php7/Slapper_v1.2.9.5.phar
