### ISSUE TITLE
Rename 'main'

### ISSUE THREAD

**Issue by Thecraftdu34** [PMPlugins/Slapper#50]
in src file rename "main" >> "Main" or server crash because ClassNotFoundException.

**Comment by jojoe77777** [comment]
Thanks for pointing that out... I had changed it on my computer but for some reason git doesn't recognise it...

**Comment by jojoe77777** [comment]
Fixed.

**Comment by BradleyJey** [comment]
Yeah, looks like you have to add sometging, like a word or change a message for it to recognize it. Lokks like github doent recignize changes on capital letters

Get Outlook for iOS




On Tue, Jun 28, 2016 at 10:42 PM -0400, "jojoe77777" <notifications@github.com> wrote:





Thanks for pointing that out... I had changed it on my computer but for some reason git doesn't recognise it...

---

**Comment by jojoe77777** [comment]
@BradleyJey That's exactly what I just did.

**Comment by BradleyJey** [comment]
XD by the way, in any future, will the name tags be fixed? Pressure

Get Outlook for iOS




On Tue, Jun 28, 2016 at 10:44 PM -0400, "jojoe77777" <notifications@github.com> wrote:





@BradleyJey That's exactly what I just did.


---

**Comment by BradleyJey** [comment]
I Meant "No Pressure xD"

Get Outlook for iOS




On Tue, Jun 28, 2016 at 10:46 PM -0400, <bradley_2025@outlook.com> wrote:





XD by the way, in any future, will the name tags be fixed? Pressure

Get Outlook for iOS




On Tue, Jun 28, 2016 at 10:44 PM -0400, "jojoe77777" <notifications@github.com> wrote:





@BradleyJey That's exactly what I just did.


---

**Comment by jojoe77777** [comment]
Yes, I am planning to fix that soon.

**Comment by BradleyJey** [comment]
Thats great! I currently own the server "@WarLordsPE" And I cant release without it being fixed.

Get Outlook for iOS




On Tue, Jun 28, 2016 at 10:47 PM -0400, "jojoe77777" <notifications@github.com> wrote:





Yes, I am planning to fix that soon.

---
