### ISSUE TITLE
Problem with Human slapper.

### ISSUE THREAD

**Issue by Thecraftdu34** [PMPlugins/Slapper#51]
When i've spawn human slapper (/slapper spawn Player 'name') so it's work but when i want to remove/edit the entity was not recognized and plugin said "That entity is not handled by slapper." 

Sorry for my bad english i'm french..

**Comment by jojoe77777** [comment]
Ohh, I thought I had missed something. My bad, fixing.

**Comment by jojoe77777** [comment]
Fixed, thanks.
