### ISSUE TITLE
Invisible Entities

### ISSUE THREAD

**Issue by MajorPlayz** [PMPlugins/Slapper#53]
Hi @jojoe77777 
I love the pugin however in the new php7 update, FallingSand and other Entities will only show the name tag when the player looks at it. This is good in some cases because I made an invisible Op Me slapper which guests can use because the can't see it. Would it be possible to have a feature to turn 'Show Nametag When I Look At It' on and off. 
I know you are currently fixing this so it is kind of set to off but in the future I think this would be a great idea. Also, sorry I posted here, I couldn't find were else to post.

Thanks
MajorPlayz

**Comment by jojoe77777** [comment]
Sorry, I don't really understand. In the latest version the name tags will show up even if you're not looking at it, and you can disable the name tag entirely with /slapper edit <id> customnamevisible 0.
Are you saying you want an option to only display name tag when looking at it?

**Comment by BradleyJey** [comment]
Hey joe, is the nametag thing fixed?

Get Outlook for iOS




On Thu, Jun 30, 2016 at 11:57 PM -0400, "jojoe77777" <notifications@github.com> wrote:





Sorry, I don't really understand. In the latest version the name tags will show up even if you're not looking at it, and you can disable the name tag entirely with /slapper edit <id> customnamevisible 0.
Are you saying you want an option to only display name tag when looking at it?

---

**Comment by jojoe77777** [comment]
@BradleyJey Yes

**Comment by BradleyJey** [comment]
Works with genisys?

Get Outlook for iOS




On Fri, Jul 1, 2016 at 12:04 AM -0400, "jojoe77777" <notifications@github.com> wrote:





@BradleyJey Yes

---

**Comment by jojoe77777** [comment]
yes it should

**Comment by MajorPlayz** [comment]
@jojoe77777 kind of however when I spawn a FallingSand entitie, firstly it spawns as 'block 0' and secondly, the nametag only appears when I look at it. I would like the feature that you said could be implemented if that is possible. Sorry if this doesn't make sense I have bad English. 

Thanks @jojoe77777

**Comment by MajorPlayz** [comment]
A feature that means when I look at it that is the only time that it displays the name tag, on and off
Thanks

**Comment by SleepSpace9** [comment]
I agree to @MajorPlayz . I think it would be a nice feature if you could choose per Slapper entity whether to show the nametag:
- always
- only when you look at it
- never

There are worlds where the nametag text is spamming you, because you see it at any distance. In this case option "*only when you look at it*" is very useful. And the other two options are also useful in other situations.

**Comment by jojoe77777** [comment]
I'll see what I can do.

**Comment by BradleyJey** [comment]
Hey joe, for some odd reason, all my floating text from falling sand dissapeared.... But i had only one human slapper and he didnt dissapear. Help?

Get Outlook for iOS




On Fri, Jul 1, 2016 at 4:06 AM -0400, "jojoe77777" <notifications@github.com> wrote:





I'll see what I can do.

---

**Comment by MajorPlayz** [comment]
@jojoe77777 Thanks
