### ISSUE TITLE
 Call to a member function getItemInHand()

### ISSUE THREAD

**Issue by Driesboy** [PMPlugins/Slapper#54]
https://github.com/iTXTech/Genisys/issues/1331#issuecomment-230088470

**Comment by jojoe77777** [comment]
Can't reproduce. Tested with latest Genisys version.

**Comment by Driesboy** [comment]
its not a slapper issues i have find the problem

**Comment by kabluinc** [comment]
@Driesboy how did you fix it?

**Comment by Driesboy** [comment]
Its fixed in genisys newest updatr
Op 10-jul.-2016 20:54 schreef "kabluinc" <notifications@github.com>:
