### ISSUE TITLE
ID 

### ISSUE THREAD

**Issue by LewBr** [PMPlugins/Slapper#56]
Unhandled exception executing command 'Slapper add human' in slapper: Call to undefined method pocketmine\Player::getSkinId()
Error: "Call to undefined method pocketmine\Player::getSkinId()" (EXCEPTION) in "/Slapper/src/slapper/Main" at line 704

day: 09.07.16

**Comment by LewBr** [comment]
$nbt = $this->makeNBT($typeToUse, $sender->getSkinData(), $sender->getSkinId(), $name, $inventory, $sender->getYaw(), $sender->getPitch(), $playerX, $playerY, $playerZ);
                              
i think you must no $sender i think its $player..

**Comment by jojoe77777** [comment]
Update your server.
