### ISSUE TITLE
Unhandled exception executing command

### ISSUE THREAD

**Issue by Dub-Boy** [PMPlugins/Slapper#59]
Getting this error running latest version of Genisys, was working fine till a few recent Genisys updates my 2 cents are they changed something that broke it.

Hoping to see a fix if possible thanks.

 [16:23:06] [Server thread/CRITICAL]: Unhandled exception executing command 'slapper spawn player Hai!' in slapper: Call to a member function getId() on null
[16:23:06] [Server thread/CRITICAL]: Error: "Call to a member function getId() on null" (EXCEPTION) in "/Slapper/src/slapper/Main" at line 706

**Comment by kaitododoyt** [comment]
the same to me

**Comment by jojoe77777** [comment]
Can you check which Genisys commit caused this?

**Comment by Dub-Boy** [comment]
@jojoe77777 wouldn't have a clue not a dev, Genisys has being renowned for breaking plugins  that's why I gave my 2 cents on what I thought

**Comment by GlitchPlayer** [comment]
Genisys is having problems onNull() on Windows 10 branch. Which is not production ready. Maybe try checking your Genisys branch?

**Comment by TheProest35YT** [comment]
![screenshot_2016-08-03-15-56-58_io mrarm mctoolbox](https://cloud.githubusercontent.com/assets/19955608/17358156/0b36a47c-5993-11e6-89f2-fd2dd1740ed6.png)
 Look at the red part

**Comment by legoboy0215** [comment]
Check the console.
