### ISSUE TITLE
Unexpected crash,  Server freeze!!

### ISSUE THREAD

**Issue by astersx** [PMPlugins/Slapper#6]
![screenshot_2016-02-12-17-45-33](https://cloud.githubusercontent.com/assets/13157548/13011986/06d13370-d1b2-11e5-91ab-16493927bee6.png)
Server Freeze and the crash dump didnt appeared :0

**Comment by Driesboy** [comment]
fixed

**Comment by Driesboy** [comment]
fixed for php5

**Comment by astersx** [comment]
Sure is fixed?  :D

**Comment by Driesboy** [comment]
yes but for villager not

**Comment by Driesboy** [comment]
fixed for zombie villager

**Comment by astersx** [comment]
So what entityes work?

**Comment by Driesboy** [comment]
i go now test

**Comment by Driesboy** [comment]
fixed

**Comment by Driesboy** [comment]
work

**Comment by Driesboy** [comment]
work for you?

**Comment by astersx** [comment]
I didnt do nothing,  im afraid of crashes,  i will test tomorow on my test server...

**Comment by Driesboy** [comment]
work for me
