### ISSUE TITLE
Can You Add Config

### ISSUE THREAD

**Issue by TheKnightGamer** [PMPlugins/Slapper#60]
Could you add a config for we can change the name of the slapper instead of writing a comannd.

**Comment by Dub-Boy** [comment]
Because apparently /slapper edit id name is too hard lol sarcasm but seriously everything can be done via commands no need for a config unless dev feels it would be useful

**Comment by TheKnightGamer** [comment]
A config is usefull for me.

**Comment by legoboy0215** [comment]
Same. But @jojoe77777 thought it will ne better and cleaner without a config.

**Comment by TheKnightGamer** [comment]
You mean worse and messy without a config.

**Comment by jojoe77777** [comment]
To support configs, I would have to change the whole saving/loading system; requiring everyone to remake all their Slapper entities. Plus I don't see the point; '/slapper edit' is relatively easy to use.
