### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by LewBr** [PMPlugins/Slapper#61]
jojoe7777, please did you have Skype? i have my plugin whit NPC and i have one problem please, can you help me whit some else? 
Twitter: @Lew_Br
Skype: leonardo.santos164

Please! Urgent. (Sorry english)

**Comment by jojoe77777** [comment]
I don't have Skype or Twitter.

**Comment by LewBr** [comment]
Did u have any contact like email? jojoe?
please..
