### ISSUE TITLE
I like to follow me with his eyes? NPC

### ISSUE THREAD

**Issue by AndroidHackPro** [PMPlugins/Slapper#62]
How I do to do the slapper follow me with his eyes? I see in LBSG servers!

**Comment by legoboy0215** [comment]
This is not added in Slapper yet.

**Comment by jojoe77777** [comment]
I think this would be too resource-intensive; and to make it look smooth you would have to send 10 packets per second to each player, so even if you just had 10 NPCs and 1 player, that's 100 packets a second.

**Comment by Yoyu666** [comment]
Pls Add this,it will be cool you can make npc looking u (*￣︶￣)
