### ISSUE TITLE
ClearSky And getSkinId Problem

### ISSUE THREAD

**Issue by FuxonPlayz** [PMPlugins/Slapper#63]
Hi :)
I get this problem when I try to spawn human entity
[code]17.07 14:45:50 [Server] Server thread/CRITICAL Unhandled exception executing command 'slapper spawn Human Team Games' in slapper: Call to undefined method pocketmine\Player::getSkinId()
17.07 14:45:50 [Server] Server thread/CRITICAL Error: "Call to undefined method pocketmine\Player::getSkinId()" (EXCEPTION) in "/Slapper_v1.2.9.7.phar/src/slapper/Main"[/code]

**Comment by FuxonPlayz** [comment]
I wasn't get this problem when I was using Genisys

**Comment by jojoe77777** [comment]
I blame ClearSky.

**Comment by TheProest35YT** [comment]
It is Clearskys fault

**Comment by TheProest35YT** [comment]
They're plugin loader sucks
