### ISSUE TITLE
Jojoe Help!

### ISSUE THREAD

**Issue by LewBr** [PMPlugins/Slapper#64]
Jojoe how can i speak whit you on privat? men i have one NPC plugin and i have one problem like: when i teleport to another world thats doesnt have the NPC is all normal, but when i teleport back to my world who haves the NPC whit my plugin crashes my Game and comes this issue:
"Could not pass event 'pocketmine\event\entity\EntityLevelChangeEvent' to 'NPC v1.2': Undefined class constant 'pocketmine\network\protocol\Info::REMOVE_PLAYER_PACKET' on NPC\Main
Error: "Undefined class constant 'pocketmine\network\protocol\Info::REMOVE_PLAYER_PACKET'" (EXCEPTION) in "/NPC-LEWBR/src/NPC/npc/NPC" at line 430

**Comment by LewBr** [comment]
and i dont know how to fix this.. i need your help, or privat chat to chatting .

**Comment by legoboy0215** [comment]
STOP SPAMMING. RemovePlayerPacket was removed from PM a while ago.
