### ISSUE TITLE
Problem "An unknown error occured while attemping to perform this command"

### ISSUE THREAD

**Issue by GamingPilot2** [PMPlugins/Slapper#65]
Hello i have a problem,
when i use /slapper spawn (Human, Bat, PrimedTnt, etc..) Test

I have the error Problem "An unknown error occured while attemping to perform this command"

I using Genisys 0.15.0

**Comment by jojoe77777** [comment]
Can you show the error here?

**Comment by GamingPilot2** [comment]
What ,

**Comment by GamingPilot2** [comment]
Please help my

**Comment by GamingPilot2** [comment]
Now i just want break my iPad because no plugin of Npc (and Slapper) works on my server ! (Error in the title)
