### ISSUE TITLE
Problem with slapper command

### ISSUE THREAD

**Issue by GamingPilot2** [PMPlugins/Slapper#67]
Hello,
Why when i try to set a command on a Slapper Human, why the command does not work ?

**Comment by jojoe77777** [comment]
What command are you typing?

**Comment by GamingPilot2** [comment]
Rca %p warp Factions

**Comment by jojoe77777** [comment]
rca {player} warp Factions

**Comment by GamingPilot2** [comment]
Hello, the command Not function too :/

**Comment by thebigsmileXD** [comment]
{player} must actually be typed, dont replace it with a name
