### ISSUE TITLE
[ERROR] "An unknown error occured while attemping to perform this command"

### ISSUE THREAD

**Issue by seaksezar** [PMPlugins/Slapper#69]
While I write "/slapper pig hog" inside game I get error "An unknown error occured while attemping to perform this command"

Please guide me what I have to do! Thanks.

**Comment by seaksezar** [comment]
-Server Information-
[Server thread/INFO]: This server is running Genisys 1.2dev-7dd3afc "Ikaros" implementing API 2.0.0 for Minecraft: Pocket Edition v0.15.0.0 alpha (protocol version 81)

**Comment by SleepSpace9** [comment]
Shouldn't it be "/slapper spawn pig hog" ?

**Comment by seaksezar** [comment]
I did tried "slapper spawn pig hog" not working. I took snap of console so you can see what I wrote and what console reply.

image report
http://imgur.com/rvyyo8a

**Comment by SleepSpace9** [comment]
Try using a more recent version of Genisys, because the name of the missing method has changed some days after your version of Genisys - getSkinName() is now getSkinId().

**Comment by legoboy0215** [comment]
^^

**Comment by ABAxStorm** [comment]
Reinstalling Slapper helped for me.

**Comment by MajorPlayz** [comment]
:D yah updating it should coz of what @sleepspace9 said

Could somebody clode the issues btw :D
