### ISSUE TITLE
2 problems.

### ISSUE THREAD

**Issue by dorkwads** [PMPlugins/Slapper#73]
I want to remove an entity but when i do /slapper id I hit the entity but doesnt show the id. Also I dont know if Im stupid or what, but I did /slapper edit (id) command kill
Then I tapped it but nothing happened. Please reply thanks! :).

**Comment by corndan** [comment]
+1

**Comment by ABAxStorm** [comment]
Not sure about the /slapper id thing, but in order to kill someone, it'd have to be /slapper edit <id> addcommand kill {player}

**Comment by SleepSpace9** [comment]
```/slapper edit [id] addcommand kill {player}```
or also possible:
```/slapper edit [id] addcommand rca {player} kill```

If you want to see the IDs of your Slapper Entities you need the permission "**slapper.seeId**".

For removing Slapper Entities with knowning the ID you can type ```/slapper remove [id]```

**Comment by ABAxStorm** [comment]
@SleepSpace9 For the second one (rca {player} kill), please keep in mind you would need OP or the permission pocketmine.command.kill

**Comment by SleepSpace9** [comment]
@ABAxStorm You only need the permission **pocketmine.command.kill.self** and this is default true.

**Comment by ABAxStorm** [comment]
@SleepSpace9 Ah, my bad. Sorry.

**Comment by corndan** [comment]
I cant click on slapper

**Comment by dorkwads** [comment]
im new to this plugin lol. But do I literally have to type {player} ?
