### ISSUE TITLE
FallingSand

### ISSUE THREAD

**Issue by MajorPlayz** [PMPlugins/Slapper#75]
On slapper Version 1.2.9.7

Whenever I do
`/slapper edit (exampleid) block 0`

On a falling sand entity, the block does not change. Also, I cannot delete the FallingSand entity when I do

`/slapper remove (exampleid)`

Or when i do 

`/slapper remove` and tap it.

Geat plugin however. Keep it up

**Comment by TheNewHEROBRINEX** [comment]
Just leave and rejoin

**Comment by Dog2puppy** [comment]
You need the chunks to reload for things like blockid and remove with FallingSand.
