### ISSUE TITLE
Fix please

### ISSUE THREAD

**Issue by MagicPandaDev** [PMPlugins/Slapper#86]
08.11 14:13:48 [Server] | Elywing thread:CRITICAL  Error: "Call to a member function getId() on null" (EXCEPTION) in "/phar_Slapper-php7_hexevAbaZvWL91x.phar/src/slapper/Main" at line 706
08.11 14:13:48 [Server] | Elywing thread:CRITICAL  Unhandled exception executing command 'slapper spawn player hi' in slapper: Call to a member function getId() on null

**Comment by dktapps** [comment]
Elywing? No thanks. I don't believe it's supported.

**Comment by MagicPandaDev** [comment]
It is, it worked before 0.16

**Comment by dktapps** [comment]
There was no such thing as Elywing before 0.16. Use pmmp/PocketMine-MP.

**Comment by jojoe77777** [comment]
I don't support Elywing.
