### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by LewBr** [PMPlugins/Slapper#88]
Hey, I have a simple question, can you answer? Please I have a problem whit 0.16 while spawning a npc in a world my client crashes, how did this even happened?? What is the update..

**Comment by LewBr** [comment]
It says I have a undefined class constant whit Data_Flags and I don't know whyyy....

**Comment by LewBr** [comment]
Print: http://prntscr.com/d6np2m

**Comment by LewBr** [comment]
Why whit my API is DATA_FLAGS not compatible?

**Comment by legoboy0215** [comment]
You will be banned from this respiratory if you keep spamming off-topic content.
